name: Release a CV

on:
  push:
    tags:
      - "*" # Any tag pushed to the repository
      
permissions:
  contents: write
  
jobs:
  # --- Job 1: Setup, render & upload artifact ---
  build:
    name: RenderCV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup environment
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
        
      - name: Install RenderCV
        run: |
          pip install -r requirements.txt
      
      - name: Find .yaml file
        id: find_cv
        run: |
          TARGET_DIR="./src"
          EXTENSION="*.yaml"
          # Find the full path of the first matching file in the target directory
          CV_FILE=$(ls -1 ${TARGET_DIR}/${EXTENSION} | head -n 1)
          if [ -z "$CV_FILE" ]; then
            echo "Error: No YAML file found in ${TARGET_DIR}."
            exit 1
          fi
          echo "filepath=$CV_FILE" >> "$GITHUB_OUTPUT"
        shell: bash
      - name: Render CV
        run: |
          RENDER_INPUT="${{ steps.find_cv.outputs.filepath }}"
          rendercv render $RENDER_INPUT
      - name: Upload output files as an artifact
        uses: actions/upload-artifact@v5
        with:
          name: cv_files
          path: rendercv_output

  # --- job 2: Download artifact and Create release ---

  release:
    name: ReleaseCV
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Download RenderCV Output
        uses: actions/download-artifact@v8
        with:
          name: cv_files
          path: rendercv_output
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rendercv_output/*_CV.pdf
            rendercv_output/*_CV.typ
          generate_release_notes: true
          make_latest: true
